require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:unit)

require 'rubocop/rake_task'
desc 'Run Ruby style checks'
RuboCop::RakeTask.new(:style)

require 'foodcritic'
FoodCritic::Rake::LintTask.new do |t|
  t.options = {
    fail_tags: ['any'],
    tags: ['~FC037']
  }
end

begin
  require 'kitchen/rake_tasks'
  Kitchen::RakeTasks.new
rescue LoadError
  puts '>>>>> Kitchen gem not loaded, omitting tasks' unless ENV['CI']
end
